[package]
name = "last_digit_of_large_number"
version = "0.1.0"
authors = ["nickmurr <nickmur72@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
